---
name: Docker Build Action
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - '*'

env:
  EDK2_TAG: edk2-stable202408.01
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/metal-stack/mini-lab-ovmf

    - name: Log in to the container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push mini-lab-ovmf image
      uses: docker/build-push-action@v6
      with:
        build-args: ${{ env.EDK2_TAG }}
        context: .
        push: true
        sbom: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
